package com.example.demo.entities;
// Generated 25/06/2019 04:43:50 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private Integer idProveedor;
	private String nombre;
	private Set productos = new HashSet(0);

	public Proveedor() {
	}

	public Proveedor(String nombre, Set productos) {
		this.nombre = nombre;
		this.productos = productos;
	}

	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
